# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip:"192.168.25.25"
  config.vm.network "public_network"
  config.vm.synced_folder "D:\\temp\\shell", "/opt/scripts"
  
  config.vm.provider "virtualbox" do |vb|
     vb.cpus = 2
     vb.memory = "1600"	 
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get -y update && sudo apt-get -y upgrade
	 sudo apt-get -y  install apache2
  SHELL
end
