Vagrant.configure("2") do |config|
   
  config.vm.define "web01" do |web01|
    web01.vm.box = "geerlingguy/centos7"
    web01.vm.network "private_network", ip: "192.168.100.100"
    web01.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "1600"
    end
    web01.vm.provision "shell", inline: <<-SHELL
      yum install httpd wget unzip -y
	  systemctl start httpd
	  systemctl enable httpd
	  cd /tmp/
	  wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip
	  unzip -o 2129_crispy_kitchen.zip
	  cp -R 2129_crispy_kitchen/* /var/www/html/
	  systemctl restart httpd
    SHELL
  end
 
  config.vm.define "wp" do |wp|
    wp.vm.box = "geerlingguy/ubuntu2004"
    wp.vm.network "private_network", ip: "192.168.10.10"
    wp.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "2600"
    end

    wp.vm.provision "shell", inline: <<-SHELL
      apt install apache2 \
                 ghostscript \
                 libapache2-mod-php \
                 mysql-server \
                 php \
                 php-bcmath \
                 php-curl \
                 php-imagick \
                 php-intl \
                 php-json \
                 php-mbstring \
                 php-mysql \
                 php-xml \
                 php-zip -y

	  sudo mkdir -p /srv/www
	  sudo chown www-data: /srv/www
	  curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
	  cp /vagrant/wordpress.conf /etc/apache2/sites-available/wordpress.conf

	  sudo a2ensite wordpress && sudo a2enmod rewrite && sudo a2dissite 000-default

	  systemctl restart apache2

	  mysql -u root -e 'CREATE DATABASE wordpress;'
	  mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "apple";'
	  mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
	  mysql -u root -e 'FLUSH PRIVILEGES;'

	  systemctl restart mysql

	  sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
	  sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
	  sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
      sudo -u www-data sed -i 's/password_here/apple/' /srv/www/wordpress/wp-config.php
	  sudo -u www-data nano /srv/www/wordpress/wp-config.php

    SHELL
  end

end
